version: '3.8'

services:
  api:
    build: .
    container_name: imersao_devops_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    # O comando do Dockerfile já inclui --reload, que é ideal para desenvolvimento.
    # CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]